name: AWS Heartbeat

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1'

permissions:
  id-token: write
  contents: read

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_HEARTBEAT_ROLE }}
          aws-region: us-east-2

      - name: Verify caller identity
        run: aws sts get-caller-identity
