name: diag-pr
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event=${{ github.event_name }}"
          echo "base=${{ github.base_ref }}"
          echo "head=${{ github.head_ref }}"
          echo "ref=${{ github.ref }}"
